name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - name: Build
        run: |
          CGO_ENABLED=0 go build -o wt-linux
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o wt-darwin
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -o wt.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            wt-darwin
            wt.exe
            wt-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}